apiVersion: v1
kind: Service
metadata:
  name: {{.OperatorName}}-webhook
  namespace: {{.OperatorNamespace}}
spec:
  ports:
    - name: webhook
      port: 9443
      targetPort: webhook
      protocol: TCP
  selector:
    app.kubernetes.io/name: odh-observability
    app.kubernetes.io/instance: odh-observability
