apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "odh-observability.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odh-observability.labels" . | nindent 4 }}
